### ISSUE TITLE
Not working properly for abstract classes default exports.

### ISSUE THREAD

**Issue by o-dasher** [JoelGamer/vscode-typescript-indexing#3]
So when you try to use this tool with a abstract class the generated index.ts output will be something like:
export { default as class}
i suppose this coming from the tool reading "export default" and assuming the next string will be the class name but in that case it would be "abstract".

**Comment by JoelGamer** [comment]
Hey @o-dasher thanks for opening an issue about this!
I've made the fix on #4 so when MS accept the new version it'll be available for use in the V-0.0.4!
